#!/bin/bash
#
# cOb4l7, 21 Oct 2016 22:36
# https://github.com/cOb4l7
# Lemonbar Configs
#

#************** Colors ******************

. $HOME/.local/bin/color-parser

#************** Panel ****************** 

PW=1366
PH=24
PX=0
PY=0


#*************** Fonts *****************

FONT1="Tewi:size=8"
FONT2="Siji:size=8"
FONT3="FontAwesome:size=8"
